export {default as Main} from './Main'
export {default as DetailsPage} from './DetailsPage'
export {default as AddPage} from './AddPage'
export {default as EditPage} from './EditPage'
export {default as LoginPage} from './LoginPage/'